PetShop/PetShop Project/Controllers/CarrinhoController.cs
using PetShop_Project.DAO;
using PetShop_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetShop_Project.Controllers
{
    public class CarrinhoController : Controller
    {
        public ActionResult Index()
        {
            var carrinho = Session["carrinho"] as Venda;

            if (carrinho == null)
            {
                carrinho = new Venda();
            }

            PopulaItens(carrinho);

            Session["carrinho"] = carrinho;

            return View(carrinho);
        }

        public ActionResult AdicionaItem(int id)
        {
            var carrinho = Session["carrinho"] as Venda;

            if (carrinho == null)
            {
                carrinho = new Venda();
            }

            var temproduto = false;
            foreach (var item in carrinho.VendaItens)
            {
                if (item.ProdutoId == id)
                {
                    temproduto = true;
                    break;
                }
            }

            if (!temproduto)
            {
                carrinho.VendaItens.Add(new VendaItem()
                {
                    ProdutoId = id,
                    Quantidade = 1
                });
            }
            else
            {
                carrinho.VendaItens.Where(vi => vi.ProdutoId == id).FirstOrDefault().Quantidade++;
            }


            AtualizaTotal(carrinho);

            Session["carrinho"] = carrinho;

            return Json(new { adicionou = true }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult RemoveItem(int id)
        {
            var carrinho = Session["carrinho"] as Venda;

            var itemParaRemover = carrinho.VendaItens.FirstOrDefault(i => i.ProdutoId == id);
            carrinho.VendaItens.Remove(itemParaRemover);

            double novoTotal = AtualizaTotal(carrinho);

            carrinho = Session["carrinho"] as Venda;

            return Json(new { removeu = true, novoTotal }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AtualizaQuantidade(int id, int quantidade)
        {
            try
            {
                var carrinho = Session["carrinho"] as Venda;
                var produto = carrinho.VendaItens.Where(vi => vi.ProdutoId == id).FirstOrDefault();
                produto.Quantidade = quantidade;
                double novoTotal = AtualizaTotal(carrinho);
                Session["carrinho"] = carrinho;
                return Json(new { atualizou = true, subtotal = Math.Round(produto.Quantidade * produto.Produto.ValorUnitario, 2), novoTotal }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { atualizou = false, msg = e.Message }, JsonRequestBehavior.AllowGet);
            }

        }

        private double AtualizaTotal(Venda venda)
        {
            venda.ValorTotal = 0;
            PopulaItens(venda);
            foreach (var item in venda.VendaItens)
            {
                venda.ValorTotal += item.Quantidade * item.Produto.ValorUnitario;
            }
            venda.ValorTotal = Math.Round(venda.ValorTotal, 2);
            return venda.ValorTotal;
        }

        private void PopulaItens(Venda venda)
        {
            var dao = new ProdutoDAO();
            foreach (var item in venda.VendaItens)
            {
                item.Produto = dao.BuscaPorId(item.ProdutoId);
            }
        }

        public ActionResult Checkout()
        {
            var user = HttpContext.Session["usuarioLogado"] as Usuario;
            var carrinho = Session["carrinho"] as Venda;

            ViewBag.Usuario = user;

            PopulaItens(carrinho);
            ViewBag.Carrinho = carrinho;
            if (user != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public ActionResult ProcessaVenda()
        {
            VendaDAO vendaDao = new VendaDAO();
            EstoqueDAO estoqueDao = new EstoqueDAO();

            var user = HttpContext.Session["usuarioLogado"] as Usuario;
            var venda = Session["carrinho"] as Venda;


            venda.UsuarioId = user.Id;
            venda.FormaPagamentoId = 1;
            venda.DataVenda = DateTime.Today;

            ProdutoDAO pdao = new ProdutoDAO();

            foreach (var item in venda.VendaItens)
            {
                var produto = pdao.BuscaPorId(item.ProdutoId);
                produto.Quantidade -= item.Quantidade;
                pdao.Atualiza(produto);

                var estoque = new Estoque()
                {
                    ProdutoId = item.ProdutoId,
                    Quantidade = item.Quantidade,
                    UsuarioAlteracaoId = user.Id,
                    DataAlteracao = DateTime.Today,
                    TipoMovimentacao = 2
                };
                estoqueDao.Adiciona(estoque);
                //vendaDao.Adiciona(venda);

                ViewBag.Venda = true;
            }

            Session["carrinho"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

PetShop/PetShop Project/Views/Carrinho/Checkout.cshtml
@{
    ViewBag.Title = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<div class="container">
    <div class="row">
        <div class="well col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <address>
                        <strong>@ViewBag.Usuario.Pessoa.Nome</strong>
                        <br>
                        @ViewBag.Usuario.Pessoa.Endereco.Logradouro
                        <br>
                        @ViewBag.Usuario.Pessoa.Endereco.Cidade,@ViewBag.Usuario.Pessoa.Endereco.Estado
                        <br>
                        @ViewBag.Usuario.Pessoa.Contato.Telefone
                    </address>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    <p>
                        <em>@DateTime.Today.ToShortDateString()</em>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="text-center">
                    <h1>RECIBO DE COMPRA</h1>
                </div>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Produtos</th>
                            <th>Referência</th>
                            <th class="text-center">Valor unitário</th>
                            <th class="text-center">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in ViewBag.Carrinho.VendaItens)
                        {
                        <tr>
                            <td class="col-md-9"><em>@item.Quantidade</em></td>
                            <td class="col-md-9"><em>@item.Produto.Nome</em></td>
                            <td class="col-md-1" style="text-align: center">@item.Produto.Id </td>
                            <td class="col-md-1 text-center"><span>R$ </span>@item.Produto.ValorUnitario</td>
                            <td class="col-md-1 text-center"><span>R$ </span>@(item.Produto.ValorUnitario * item.Quantidade)</td>
                        </tr>
                        }
                        <tr>
                            <td>   </td>
                            <td>   </td>
                            <td class="text-right"><h4><strong>Total: </strong></h4></td>
                            <td class="text-center text-danger"><h4><strong><span>R$ </span>@ViewBag.Carrinho.ValorTotal</strong></h4></td>
                        </tr>
                    </tbody>
                </table>
                <button onclick="window.location.href = '@Url.Action("ProcessaVenda","Carrinho")'" type="button" class="btn btn-success btn-lg btn-block">
                    Finalizar Compra   <span class="glyphicon glyphicon-chevron-right"></span>
                </button>
            </div>
        </div>
    </div>
</div>

PetShop/PetShop Project/Views/Carrinho/Index.cshtml
@model PetShop_Project.Models.Venda

@{
    /**/

    /**/

    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="main">
    <div class="container">
        <!-- BEGIN SIDEBAR & CONTENT -->
        <div class="row margin-bottom-40">
            <!-- BEGIN CONTENT -->
            <div class="col-md-12 col-sm-12">
                <h1>Carrinho de compras</h1>
                <div class="goods-page">
                    <div class="goods-data clearfix">
                        <div class="table-wrapper-responsive">
                            <table summary="CARRINHO">
                                <tr>
                                    <th class="goods-page-image">Imagem</th>
                                    <th class="goods-page-description">Produto</th>
                                    <th class="goods-page-quantity">Quantidade</th>
                                    <th class="goods-page-price">Preço Unitário</th>
                                    <th class="goods-page-total" colspan="2">Total</th>
                                </tr>

                                @foreach (var item in Model.VendaItens)
                                {
                                    string img = "";
                                    if (item.Produto.Imagem != null)
                                    {
                                        var base64 = Convert.ToBase64String(item.Produto.Imagem);
                                        var extensao = "jpeg";

                                        img = $"data:image/{extensao};base64,{base64}";

                                    }


                                    <tr>
                                        <td class="goods-page-image">
                                            <a href="@Url.Action("Detalhes", "DetalhesProduto", new { id = item.Produto.Id })"><img src="@img" alt=""></a>
                                        </td>
                                        <td class="goods-page-description">
                                            <h3><a href="@Url.Action("Detalhes", "DetalhesProduto", new { id = item.Produto.Id })">@item.Produto.Nome</a></h3>
                                        </td>
                                        <td class="goods-page-ref-no">
                                            ID[@item.Produto.Id]
                                        </td>
                                        <td class="goods-page-quantity">
                                            <div class="product-quantity">
                                                <input id="product-quantity" type="number" value="@item.Quantidade" max="@item.Produto.Quantidade" readonly class="form-control input-sm">
                                            </div>
                                        </td>
                                        <td class="goods-page-price">
                                            <strong><span>R$ @item.Produto.ValorUnitario</span></strong>
                                        </td>
                                        <td class="goods-page-total">
                                            <strong>
                                                <span>R$ </span>
                                                <span class="subtotalProduto">@(item.Produto.ValorUnitario * item.Quantidade)</span>
                                            </strong>
                                        </td>
                                        <td class="del-goods-col" id="@item.Produto.Id">
                                            <a class="del-goods btnRemover">&nbsp;</a>
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>

                        <div class="shopping-total">
                            <ul>
                                <li>
                                    <em>TOTAL</em>
                                    <strong class="price"><span>R$ </span><span id="totalCarrinho">@Model.ValorTotal.ToString()</span></strong>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <button class="btn btn-default" type="submit">Continuar comprando <i class="fa fa-shopping-cart"></i></button>
                    <button class="btn btn-primary" type="submit" onclick="window.location.href = '@Url.Action("Checkout","Carrinho")'">Finalizar compra <i class="fa fa-check"></i></button>
                </div>
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END SIDEBAR & CONTENT -->
    </div>
</div>

<script src="~/Content/assets/plugins/jquery.min.js" type="text/javascript"></script>
<script src="~/Content/assets/plugins/bootstrap-touchspin/bootstrap.touchspin.js" type="text/javascript"></script>

<script src="~/Content/assets/corporate/scripts/layout.js" type="text/javascript"></script>
<script type="text/javascript">
    jQuery(document).ready(function () {
        Layout.initTouchspin();
        jQuery(".quantity-down, .quantity-up").click(function () {
            var subtotalInput = $(this).closest('tr').find(".goods-page-total").find("strong").find(".subtotalProduto");
            var id = $(this).closest('tr').find(".del-goods-col").prop("id");
            var quantidade = $(this).parent().parent().find("#product-quantity").val();
            $.ajax({
                type: "POST",
                url: "/Carrinho/AtualizaQuantidade",
                dataType: "json",
                data: { id: id, quantidade: quantidade },
                success: function (response) {
                    if (response.atualizou) {
                        subtotalInput.text(response.subtotal);
                        subtotalInput.text(subtotalInput.text().replace(".", ","));
                        $("#totalCarrinho").text(response.novoTotal);
                        $("#totalCarrinho").text($("#totalCarrinho").text().replace(".", ","));
                    } else {
                        console.log(response.msg);
                    }
                }
            });
        });
    });

    $(".btnRemover").click(function () {
        var tr = $(this).closest('tr');
        var idProduto = $(this).parent().prop("id");
        $.ajax({
            type: "POST",
            url: "/Carrinho/RemoveItem/" + idProduto,
            dataType: "json",
            success: function (response) {
                if (response.removeu) {
                    tr.remove();
                    $("#totalCarrinho").text(response.novoTotal);
                    $("#totalCarrinho").text($("#totalCarrinho").text().replace(".", ","));
                    $.notify("Produto removido com sucesso!", "success", { position: "top center" });

                }
            }
        });
    });


</script>